
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xf3\xc8\xd2\x91T\xeeb\x7f\xd5)Y1\xfb\xac\xe5\xc8'
    
_lr_action_items = {'NUEVA_LINEA':([10,11,12,13,14,16,],[15,-9,-10,-8,-6,-7,]),'NO_TERMINAL':([0,4,6,9,11,12,13,14,],[1,-4,-3,11,-9,-10,-8,11,]),'ESPACIO':([1,3,4,7,8,],[-2,4,4,-5,4,]),'EPSILON':([4,6,9,11,12,13,14,],[-4,-3,12,-9,-10,-8,12,]),'TERMINAL':([4,6,9,11,12,13,14,],[-4,-3,13,-9,-10,-8,13,]),'FLECHA':([4,5,6,],[-4,7,-3,]),'$end':([2,15,],[0,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'parte_derecha':([9,14,],[10,16,]),'token':([9,14,],[14,14,]),'flecha':([5,],[8,]),'produccion':([0,],[2,]),'parte_izquierda':([0,],[3,]),'espacios':([3,4,8,],[5,6,9,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> produccion","S'",1,None,None,None),
  ('produccion -> parte_izquierda espacios flecha espacios parte_derecha NUEVA_LINEA','produccion',6,'p_produccion','lector.py',94),
  ('parte_izquierda -> NO_TERMINAL','parte_izquierda',1,'p_parte_izquierda','lector.py',99),
  ('espacios -> ESPACIO espacios','espacios',2,'p_espacios','lector.py',105),
  ('espacios -> ESPACIO','espacios',1,'p_espacios','lector.py',106),
  ('flecha -> FLECHA','flecha',1,'p_flecha','lector.py',111),
  ('parte_derecha -> token','parte_derecha',1,'p_parte_derecha','lector.py',117),
  ('parte_derecha -> token parte_derecha','parte_derecha',2,'p_parte_derecha','lector.py',118),
  ('token -> TERMINAL','token',1,'p_token','lector.py',123),
  ('token -> NO_TERMINAL','token',1,'p_token','lector.py',124),
  ('token -> EPSILON','token',1,'p_token','lector.py',125),
]
