
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xd1\xbd\x88\xc6\x8e~\x13\xf9\xd3FN\xa4\xfa\xe3\x18\x94'
    
_lr_action_items = {'SPAN_STYLE':([6,9,11,],[10,12,14,]),'ID_NOMBRE_DE_LA_MADRE':([8,],[11,]),'ID_NOMBRE_DEL_PADRE':([5,],[9,]),'SPAN_CIERRE':([13,15,17,],[16,18,19,]),'ID_NOMBRE_COMPLETO':([2,],[6,]),'NOMBRE':([10,12,14,],[13,15,17,]),'SPAN_INICIO':([0,1,4,16,18,],[2,5,8,-2,-3,]),'$end':([3,7,19,],[0,-1,-4,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'nombreDelPadre':([1,],[4,]),'nombre':([0,],[1,]),'nombreDeLaMadre':([4,],[7,]),'elementos':([0,],[3,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> elementos","S'",1,None,None,None),
  ('elementos -> nombre nombreDelPadre nombreDeLaMadre','elementos',3,'p_elementos','tseParser.py',128),
  ('nombre -> SPAN_INICIO ID_NOMBRE_COMPLETO SPAN_STYLE NOMBRE SPAN_CIERRE','nombre',5,'p_nombre','tseParser.py',132),
  ('nombreDelPadre -> SPAN_INICIO ID_NOMBRE_DEL_PADRE SPAN_STYLE NOMBRE SPAN_CIERRE','nombreDelPadre',5,'p_nombreDelPadre','tseParser.py',138),
  ('nombreDeLaMadre -> SPAN_INICIO ID_NOMBRE_DE_LA_MADRE SPAN_STYLE NOMBRE SPAN_CIERRE','nombreDeLaMadre',5,'p_nombreDeLaMadre','tseParser.py',144),
]
