
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xc9\x87\xd0\x80i\xf7TB\xa6\xae\x0f\x1b\x1f\x05#\xad'
    
_lr_action_items = {'PARTE_DERECHA_LABEL':([9,],[10,]),'NOMBRE_NO_ENCONTRADO':([0,],[1,]),'NOMBRE':([8,],[9,]),'PARTE_IZQUIERDA_LABEL':([0,5,10,],[6,6,-5,]),'CEDULA':([6,],[8,]),'$end':([1,2,3,4,5,7,10,],[-6,0,-2,-1,-4,-3,-5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'nombres':([0,5,],[3,7,]),'nombre_no_encontrado':([0,],[4,]),'buscar_nombres':([0,],[2,]),'nombre':([0,5,],[5,5,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> buscar_nombres","S'",1,None,None,None),
  ('buscar_nombres -> nombre_no_encontrado','buscar_nombres',1,'p_buscar_nombres','/Users/yo/Desktop/python/003/tseNameParser.py',130),
  ('buscar_nombres -> nombres','buscar_nombres',1,'p_buscar_nombres','/Users/yo/Desktop/python/003/tseNameParser.py',131),
  ('nombres -> nombre nombres','nombres',2,'p_nombres','/Users/yo/Desktop/python/003/tseNameParser.py',134),
  ('nombres -> nombre','nombres',1,'p_nombres','/Users/yo/Desktop/python/003/tseNameParser.py',135),
  ('nombre -> PARTE_IZQUIERDA_LABEL CEDULA NOMBRE PARTE_DERECHA_LABEL','nombre',4,'p_nombre','/Users/yo/Desktop/python/003/tseNameParser.py',138),
  ('nombre_no_encontrado -> NOMBRE_NO_ENCONTRADO','nombre_no_encontrado',1,'p_nombre_no_encontrado','/Users/yo/Desktop/python/003/tseNameParser.py',143),
]
